spring:
  application:
    name: SpringAlBot

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b
          temperature: 0.2
server:
  port: 8080
